### ISSUE TITLE
[Feature Request] Disable Authentication

### ISSUE THREAD

**Issue by kevinoconnor7** [darkalfx/requestrr#103]
I put everything behind a reverse proxy that also takes care of authentication and therefore would prefer to have auth entirely disabled. It seems like the account isn't actually important and really just serves to password protect the settings, so a simple option to disable authentication would be nice!

**Comment by darkalfx** [comment]
This is now available in the latest release in the settings page in the web portal

**Comment by kevinoconnor7** [comment]
Perfect! Thank you so much for your hard work!
