### ISSUE TITLE
[Bug] TVDB Links Broken

### ISSUE THREAD

**Issue by vember31** [darkalfx/requestrr#104]
Hi,

First of all, love Requestrr.  I wanted to call out that for some time, it appears that the TVDB links when requesting TV shows are broken.  The notification itself seems to find it correctly; it is just the link itself that links out to the wrong show.  

For example, I'm searching for a show called 'The Terror' as shown in the below screenshot.  It correctly finds the show and displays it properly in the notification (the including the overview, where it airs, etc), and even knows that it is already requested - so the linkage between Overseerr and Plex is working as expected.  However, the blue link itself to the TVDB for the TV show takes me to [this link](https://www.thetvdb.com/series/my-life-as-a-popat) (TVDB 75191) instead of the [appropriate link ](https://www.thetvdb.com/?id=322191&tab=series)(TVDB ID 322191).  The issues seems to be that the link is generated using the wrong TVDB ID.  The title of the link is correct too; just links out to the wrong TVDB series ID.  I'm not sure where the 75191 is coming from.

It's a small issue but wanted to call it out as I didn't see a different issue submitted for it.  Let me know if I can clarify anything or provide more details / examples!

Thanks again for all of the work on Requestrr :)

![image](https://user-images.githubusercontent.com/17370796/132727081-1562f8e3-3b89-4339-a6b7-612c0c30a40f.png)

**Comment by darkalfx** [comment]
Yeah that's definitely a problem, I'll fix it in the next update, thanks for the report!

**Comment by darkalfx** [comment]
This is fixed in the latest update
