### ISSUE TITLE
Failed to load /root/libhostpolicy.so Docker Arm64

### ISSUE THREAD

**Issue by mLgz0rn** [darkalfx/requestrr#105]
After updating to v1.0.18 on arm64 I get the following error and the bot never starts

```
Failed to load /root/libhostpolicy.so, error: /root/libhostpolicy.so: file too short
An error occurred while loading required library libhostpolicy.so from [/root/]
```
Rolling back to v1.0.17 and it starts without any issues.

Kind regards

**Comment by darkalfx** [comment]
What device are you running this on?

**Comment by mLgz0rn** [comment]
A Raspberry Pi 4 8gb

**Comment by darkalfx** [comment]
I'll try to set up mine and see whats up

**Comment by mLgz0rn** [comment]
I just tried updating to 1.0.20, and there does not seem to be an issue anymore!
Don't know if you fixed it or if it somehow was on my end, but it works now! :D
