### ISSUE TITLE
"Your request was denied by the provider due to insufficient permissions or quota limits" v1.0.21 

### ISSUE THREAD

**Issue by paxos** [darkalfx/requestrr#109]
Using v1.0.21 with overseerr

![Screen Shot 2021-09-30 at 00 32 56](https://user-images.githubusercontent.com/121539/135407749-ff7e24a8-9e98-4495-9f44-4ff291f772cb.png)

Definitely no quotas or restricted permission are setup. Also no Overseerr user id is setup.

Any hints how to debug this?

**Comment by darkalfx** [comment]
Is your bot connected to Overseerr? or directly to Radarr?

**Comment by paxos** [comment]
Directly connected to Overseerr

**Comment by darkalfx** [comment]
There's two possibilities that I see:

1. You forgot to deactivate **CSRF protection** in Overseerr's General Settings page
2. The overseerr user that your discord user links to doesnt have permissions to request things in Overseerr

**Comment by paxos** [comment]
You are absolutely right; it was CSRF turned on.
Sorry, I assumed it stopped working after updating. But it was clearly me messing the setting up.

Thanks for the hint & thank you for your great work!
