### ISSUE TITLE
Feature Request - Forcing Search & Follow

### ISSUE THREAD

**Issue by b101marc** [darkalfx/requestrr#116]
Hello,

Hope this is the right place to post this. I wanted to request a couple of features I'd seen elsewhere but nothing runs as reliably for me as requestrr.

1. When requesting an item and downloads are handled via Sonarr or Radarr forcing a new search for content despite already having been requested. Example: I requested TV Show/Movie "X" a week ago but no items downloaded. If requested again, forcing a new search for said content in Sonarr or Radarr.
2. Following a show. When a new episode of a TV show is downloaded/marked as available, notify users who followed this show that a new episode is available. Original requester isn't the only person notified of this new episode. Could be achieved by using a command such as `/follow tv ted lasso`.

Hope that's clear. Happy to try and explain further if needed.

**Comment by darkalfx** [comment]
Greetings,

For your second point that feature is actually planned and will be implemented, so no worries about that.

For your first point, shouldn't Sonarr/Radarr automatically keep looking for new content if its been a few weeks?

**Comment by b101marc** [comment]
> For your first point, shouldn't Sonarr/Radarr automatically keep looking for new content if its been a few weeks?

I suppose you're right, sorry brain fart.

> For your second point that feature is actually planned and will be implemented, so no worries about that.

Great!
