### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by thomasdelorge** [darkalfx/requestrr#118]
Hello everyone,

Untill few days, my Requestrr bot don't reply in Discord :( I check discord settings and Radarr settings and test are OK.

I found this in logs but I don't know what to do : 

[2021-10-05 19:06:00 +02:00] [0   /            ] [Crit ] There was an error registering application commands
DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 403
   at DSharpPlus.Net.DiscordApiClient.BulkOverwriteGuildApplicationCommandsAsync(UInt64 application_id, UInt64 guild_id, IEnumerable`1 commands)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass38_0.<<RegisterCommands>b__0>d.MoveNext()

Exeption seem like to come from DSharpPlus to communicate with Discord but i'm stuck, someone could help me ?

**Comment by darkalfx** [comment]
I would recommend that you check this out first:

__**Here's what's changed**__

The bot is now using slash commands `/` the old way of using commands with the prefix `!` is gone.

__**How do I correctly migrate my bot?**__

First update your bot to the latest version.

Then kick the bot from your server(s), go in Requestrr's web portal in the Chat Client page and re-invite your bot to your servers using the **COPY LINK** button to get your new link.

Once its inside your server(s), restart it then you should be good to go

**Comment by thomasdelorge** [comment]
Love you, kicked him and added him again : work perfectly ! :)
