### ISSUE TITLE
Requestrr doesnt work with mobile discord

### ISSUE THREAD

**Issue by ragekitty** [darkalfx/requestrr#129]
I am having issues with the mobile discord and getting requestrr to work on mobile. I cant seem to find anybody else having the same issue. It does seem like a discord problem rather than a requestrr issue. [image](https://i.ibb.co/vhWvLHP/Screensho-Discord.jpg) I can see the requester but when I click on it and fill it out the bot doesn't respond.

**Comment by BuggeringHell** [comment]
I also ran into this issue on Android, force closing/opening the app fixed it
