### ISSUE TITLE
[Feature Request] Split Sonarr Instance Catagories

### ISSUE THREAD

**Issue by Heavybullets8** [darkalfx/requestrr#152]
Overseerr/Jellyseerr allow for both Anime and regular series to be added to a sonarr instance. 

![image](https://user-images.githubusercontent.com/20793231/185269023-d5e693ae-8496-44f4-85b0-4889603c401f.png)
> As shown here, both anime and any other series type can be selected.

It would be nice if requestrr would allow us to split them up to two different folders as well. 

Anime
> `/media/anime`

Tv Shows 
> `/media/tvshows`

<br >

As you can see here I only have the option between `Series` and `Kids Series`, there is no option for `Anime` so then I could split up where the files are going

![image](https://user-images.githubusercontent.com/20793231/185269394-6e9ad3b9-f75b-428b-b5ce-52079ec64f43.png)

**Comment by darkalfx** [comment]
You can make an anime category in Requestrr and just apply the same settings you put in Overseerr for your instance.

**Comment by Heavybullets8** [comment]
Huh. You're totally right. I'm not sure how I didn't realize that..

Sorry about that haha. I appreciate your work, I'll close this now.
