### ISSUE TITLE
Requestrr portal not accessible behind nginx proxy

### ISSUE THREAD

**Issue by Iguana9999phil** [darkalfx/requestrr#16]
Having a hard time to get the webportal exposed behind an nginx proxy. Even forwarding the port 4545 to the bot doesn't let me load the webportal externally. Is it only serving the webportal on localhost?

**Comment by darkalfx** [comment]
A lot of people have it set up with a reverse proxy setup, usually via a subdomain, and it works great.

Unfortunately I am not personally familiar with reverse proxies, but perhaps someone in the discord server would be able to help you.

**Comment by RobinMM** [comment]
Its working fine behind a proxy. This issue can be closed :)
