### ISSUE TITLE
Running Requestrr in Windows 11 Pro Build (1000.22662.1000.0)

### ISSUE THREAD

**Issue by RyanK2215** [darkalfx/requestrr#182]
I've configured Requestrr to notify users via channels in discord when content is added to Plex, however after every Windows restart I'm getting a repeat notification for one particular movie that's already been added to Plex and already sent its initial notification. Every time I restart my Windows VM the notification repeats itself as the Requestrr.WebAPI is set up to start on Windows Startup. Was not able to identify a work around with Google.

**Comment by apriac** [comment]
Without seeing your setup it's hard for me to say but there's probably an issue with your notifications file. 

It's called notifications.json and should be in a folder called config. Check if there is a movie remaining in it.
It should look like this :

{
  "Movies": [], <- there should be nothing here or in your case the movie that gets notified after each restart
  "TvShows": [],
  "Music": []
}

**Comment by RyanK2215** [comment]
> Without seeing your setup it's hard for me to say but there's probably an issue with your notifications file.
> 
> It's called notifications.json and should be in a folder called config. Check if there is a movie remaining in it. It should look like this :
> 
> { "Movies": [], <- there should be nothing here or in your case the movie that gets notified after each restart "TvShows": [], "Music": [] }

OK! My Notifications file did have some junk in it, and I have updated it. Does removing that information prevent new updates for new downloads from arriving as I would expect?

**Comment by apriac** [comment]
It would prevent old request that would not have already been completed to be send.

I probably should have told you to only remove the movie that was already completed from that list, sorry about that 😑

To have a bit more context, the file notifications.json keeps track of all movies requested. Periodically, Requestrr will check what's newly available in Sonarr / Radarr and if it's in this file will send a notification and remove the notification from the list.

So if there is a movie / tv shows that keeps being notified when it shoud not try to stop Requestrr and only remove this line from the notifications.json file.
