### ISSUE TITLE
Error requesting additional seasons for a series

### ISSUE THREAD

**Issue by esran** [darkalfx/requestrr#188]
Once a series has been added with a single season, trying to request another season fails with the following in discord:

![image](https://github.com/darkalfx/requestrr/assets/5937837/62b86939-ea7f-4d18-b2ce-93a5da911618)

Looks like a problem parsing JSON response from sonarr. The new season does get set to monitored but not search is kicked off.

[requestrr-error.txt](https://github.com/darkalfx/requestrr/files/13792133/requestrr-error.txt)

Sonarr version: 4.0.0.737 (nightly-628449d by hotio)

**Comment by thomst08** [comment]
Hello,

I checked and recreated this issue using the latest version of Sonarr V4, Requestrr was submitting data in an incorrect type.
I have created a pull request to fix the issue in a new release:
https://github.com/darkalfx/requestrr/pull/189

**Comment by darkalfx** [comment]
Support for Sonarr V4 has been added
