### ISSUE TITLE
Your request was denied by the provider due to an insufficient quota limit or insufficient roles.

### ISSUE THREAD

**Issue by morganzero** [darkalfx/requestrr#19]
Hi,

Loving Requestrr. But I have an issue, please see image below;

![Skärmavbild 2020-04-08 kl  13 31 27](https://user-images.githubusercontent.com/57449785/78779440-430d6880-799d-11ea-8adb-3d065cf19341.png)

And this happens to every request I make that I don't already have in library. I've checked ombi and it looks good and I'm out of ideas!

**Comment by darkalfx** [comment]
Hello,

The bot is telling you that the corresponding user in Ombi, either the default user specified in the config or the linked one in Ombi, doesn’t have enough quota or permissions to make the request.

The user in Ombi needs to have either admin/request Tv/Auto approve Tv roles, while also not having the disabled role and also have quotas remaining in Ombi.

**Comment by morganzero** [comment]
I have not given it the admin role, but i have given the discord-user the roles you can see here:
![image](https://user-images.githubusercontent.com/57449785/78792460-6e9a4e00-79b1-11ea-9361-d0f5db6b4fff.png)

And the quotas are 0 per default. I have tried setting limit to 10000 - which didn't work either.
![image](https://user-images.githubusercontent.com/57449785/78792491-7659f280-79b1-11ea-8b5d-cc7cedc2f1fc.png)

Any ideas?

**Comment by darkalfx** [comment]
This looks good to me.

Did you correctly link the discord user you are using to this user? (Via notifications preferences)

**Comment by morganzero** [comment]
If you mean if I copied the User ID in discord and pasted it like in this picture? - then yes :)
![image](https://user-images.githubusercontent.com/57449785/78797688-51b54900-79b8-11ea-9ed1-252c101021ce.png)

**Comment by darkalfx** [comment]
Can you confirm that the ID is correct and that there isn’t another user with this ID in their notifications settings?

Also did you set a default user for Ombi in Requestrr and what version of the bot are you using?

**Comment by morganzero** [comment]
I can confirm that the user id matches between ombi notifications settings and the discord user id. But now that I think of it maybe putting the user id as a default user in Requestrr wasn't a smart move?

The version of the web gui is © 2020 Requestrr (v1.0.9) and if it helps i'm running docker image: darkalfx/requestrr:latest

**Comment by morganzero** [comment]
BOOM!
Removing the User ID from within Requestrr did the job. I guess I was wrong about putting in the User ID in there. Thanks alot for baring with me. And great work!
![Skärmavbild 2020-04-08 kl  17 11 28](https://user-images.githubusercontent.com/57449785/78800852-3ba98780-79bc-11ea-8594-f7dfc11efe63.png)
