### ISSUE TITLE
grab season packs (sonarr)

### ISSUE THREAD

**Issue by eckozen84** [darkalfx/requestrr#20]
The tracker that I use for sonarr usually only has season packs for shows that have finished airing.

When I add a series via requestrr that has finished airing some time ago, it attempts to grab individual episodes which do not exist on the tracker anymore. Is there a way to have it request a season pack first and if no match is found, attempt to grab individual episodes?

I am currently using sonarr v3

**Comment by darkalfx** [comment]
Greetings,

Just to be make sure that there isn’t a problem elsewhere, whenever you add a **completely new series** via Requestrr, it will not search for every episode individually, it will do exactly the same as when you add it directly through Sonarr and check the “start search for missing episodes”.

If that doesn’t work as you would expect, I’m not sure there anything I can do.

**Comment by eckozen84** [comment]
@darkalfx Thank you for the clarity. It would seem then the issue is on my end. I will check my setup again and provide any feedback if I discover something. I'll mark this as closed.
