### ISSUE TITLE
Add support for non root docker container user and PUID and PGID env variables

### ISSUE THREAD

**Issue by arpitgupta** [darkalfx/requestrr#21]
Running docker container with non root user leads to issues where you can see issues like

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd ("/root") set in config.json failed: permission denied": unknown.
```

```
System.UnauthorizedAccessException: Access to the path '/.dotnet' is denied. ---> System.IO.IOException: Permission denied
```

This is likely due to the root folder having 700 permission
```
root@requestrr:~# ls -ld /root
drwx------ 6 root root 4096 Apr 17 22:47 /root
```

We should also see if we can add support for PGID and PUID env vars so we can have a cleaner integration with Synology docker ui.

**Comment by arpitgupta** [comment]
Looks like PGID/PUID support would be some work. See https://www.reddit.com/r/docker/comments/9iwe3t/where_can_i_find_out_how_puid_and_pgid_are_used/ for reference.

May be long term we should see how linuxserver can support this image?

**Comment by hotio** [comment]
I've made a docker container with PUID and PGID support
https://hub.docker.com/r/hotio/requestrr
![screenshot](https://user-images.githubusercontent.com/26902309/88083541-7ad2a180-cb83-11ea-8871-d9f161abdd2b.png)
