### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by kenlefeb** [darkalfx/requestrr#3]
I noticed that you have maintained a very flat namespace hierarchy, so types that are related, like the Discord chat client, are not encapsulated into their own namespaces. Did you do this for a particular reason?

If I want to contribute a new Chat Client (and/or new Download Clients), it would be nice to have a separate namespace to contain the types. There are likely to be a lot of similar but not quite the same types for different clients.

I had Resharper "fix" all the namespaces in the your project, to make them align to the folders, and there were 44 files changed: I encourage you to consider making this change earlier, rather than later, so as you attract contributors to the code base, things stay more organized.

**Comment by darkalfx** [comment]
That is a very good point, I recently switch my dev machine to Mac OS and I don't have Resharper VSCode, though I'm sure there's quite a few extensions to help with the renaming of the namespaces.

I'll fix them shortly, thanks for the feedback!

**Comment by kenlefeb** [comment]
I bet JetBrains would give you a free license to Rider, in exchange for an icon on your open source project repo. They're pretty generous with open source projects.

If you want, I can give you a pull request with refactored namespaces, too.

**Comment by darkalfx** [comment]
I renamed all the namespaces, thanks for the feedback, I appreciate it!
