### ISSUE TITLE
[Bug]  Bot Presence Doesn't Update With Command Prefix

### ISSUE THREAD

**Issue by mrjester888** [darkalfx/requestrr#31]
In user list, the bot has subtext stating "Playing !help"  The help portion should change based on the configured command prefix.  

My command prefix is configured as !j right now.
![image](https://user-images.githubusercontent.com/5603366/82825836-ef39de80-9e79-11ea-8d83-4a6b09ad280c.png)

Mellow supports this, as well as changes the text to "Listening to" to make it a bit more clear on what the bot is doing.  https://discord.com/developers/docs/rich-presence/how-to

**Comment by darkalfx** [comment]
You can change the text shown to anything you want in the Discord configuration for the bot, the field is called status or status message, what you're seeing is just the default value.

**Comment by mrjester888** [comment]
I didn't even see that field there.  Thank you.
