### ISSUE TITLE
Option to specify PUID and PGID in docker command

### ISSUE THREAD

**Issue by kneelesh48** [darkalfx/requestrr#32]
I tried adding those flags in docker-compose file but the container still installed as my current user and not the specified user. This is a security risk and should be fixed.

**Comment by hotio** [comment]
@kneelesh48 see https://hub.docker.com/r/hotio/requestrr

**Comment by darkalfx** [comment]
You can also now use:
[https://hub.docker.com/r/linuxserver/requestrr](https://hub.docker.com/r/linuxserver/requestrr)
