### ISSUE TITLE
Issues following redirects for different URL bases.

### ISSUE THREAD

**Issue by FozzieBear** [darkalfx/requestrr#4]
It appears that when using a URL Base setting within Sonarr\Radarr, Requestrr has issues following the redirect that's returned for POSTs. It appears to be switching to a GET request which also no longer includes the API Key. For example below, a URL Base of /sonarr is configured for use behind a reverse proxy. 

>POST /api/v3/series HTTP/1.1
>Host: sonarr_v3:8989
>Content-Type: application/json
>X-Api-Key: \*\*snip\*\*
>Content-Length: 415
>
>{"title":"Outsiders","qualityProfileId":6,"profileId":6,"languageProfileId":1,"titleSlug":"outsiders","monitored":true,"images":[],"tvdbId":303236,"tags":[],"seriesType":"standard","year":2016,"seasonFolder":true,"rootFolderPath":"/tv","id":null,"seasons":[{"seasonNumber":0,"monitored":false},{"seasonNumber":1,"monitored":true},{"seasonNumber":2,"monitored":false}],"addOptions":{"searchForMissingEpisodes":true}}
>
>HTTP/1.1 303 See Other
>X-Application-Version: 3.0.3.717
>Location: /sonarr/api/v3/series
>X-ApplicationVersion: 3.0.3.717
>Cache-Control: no-cache, no-store, must-revalidate, max-age=0
>Pragma: no-cache
>Expires: 0
>Access-Control-Allow-Origin: *
>Content-Type: text/html
>Server: Mono-HTTPAPI/1.0
>Date: Sun, 15 Mar 2020 21:38:27 GMT
>Content-Length: 0
>Keep-Alive: timeout=15,max=78
>
>GET /sonarr/api/v3/series HTTP/1.1
>Host: sonarr_v3:8989
>
>HTTP/1.1 401 Unauthorized
>X-Application-Version: 3.0.3.717
>Cache-Control: no-cache, no-store, must-revalidate, max-age=0
>Pragma: no-cache
>Expires: 0
>Content-Type: application/json; charset=utf-8
>Server: Mono-HTTPAPI/1.0
>Date: Sun, 15 Mar 2020 21:38:27 GMT
>Transfer-Encoding: chunked
>Keep-Alive: timeout=15,max=77
>
>1d
>{
>  "error": "Unauthorized"
>}
>0

This shows up in Sonarr as the the following error due to the GET request with no API key:

>20-3-15 14:38:27.5|Info|Auth|Auth-Unauthorized ip 192.168.16.7 url 'http://sonarr_v3:8989/sonarr/api/v3/series'

**Comment by darkalfx** [comment]
You're absolutely correct, right now it doesn't handle the base URLs correctly at all.
It's going to be fixed in v1.0.1 which is most likely coming out tomorrow or Tuesday at the latest.

Keep an eye out!

**Comment by darkalfx** [comment]
With the release of V.1.0.1, you can now configure the base urls in the web portal.

This issue is now resolved.
