### ISSUE TITLE
[Bug] v1.0.9+ fails to start on macOS: "Requestrr.Webapi" is damaged and can't be opened.

### ISSUE THREAD

**Issue by twilsonco** [darkalfx/requestrr#45]
After following the one-step macOS installation instructions, I open Requestrr from its directory using `./Requestrr.WebApi` and a macOS system dialog opens that states *“Requestrr.WebApi” is damaged and can’t be opened. You should move it to the Trash.*

This is the behavior with every release of `requestrr-osx-x64.zip` back to v1.0.9.

v1.0.8 opens and runs fine. (well, it won't load the web configuration interface but the bot is perfectly functional in Discord)

I'm on macOS 10.15.3 on a 2012 Mac Mini

**Comment by darkalfx** [comment]
Please confirm if this happens with the latest release I just pushed out, v1.0.13

**Comment by twilsonco** [comment]
v1.0.13 runs without the error with what looks like full functionality. 
I did, however have to `chmod +x Requestrr.Webapi`, but that's a different thing.
