### ISSUE TITLE
Option to enable unmonitored/monitored state on tv and movies

### ISSUE THREAD

**Issue by AndreasAsen** [darkalfx/requestrr#5]
Is it possible to add option to enable Unmonitored/Monitored to movies and TV when the movie gets added to radarr or sonarr? Because right now all media gets added as monitored.

**Comment by darkalfx** [comment]
Greetings!

This feature has already been added, it will ship with the next release which should be today or tomorrow:

![image](https://user-images.githubusercontent.com/22474506/76774939-03c37180-677b-11ea-9a24-cb561588e662.png)

Keep an eye out!

**Comment by AndreasAsen** [comment]
Awesome! That is good news. Thanks for an awesome application :D

**Comment by darkalfx** [comment]
V.1.0.1 has been released, this feature is now available.
Enjoy!
