### ISSUE TITLE
[Feature Request] - Sort Movie requests into Folder by [imdb?] Genre

### ISSUE THREAD

**Issue by nailz1000** [darkalfx/requestrr#50]
I've managed to separate movies in Radarr into their respective genres, and would like requests to choose the appropriate destination folder based on movie Genre. Is this possible?

**Comment by ahstevens** [comment]
I would like something similar.

Right now, I have three separate Requestrr instances running: one that handles Hollywood movies, one that handles Horror movies, and one that handles Documentary features; each of these bot instances listen for requests in their own dedicated channels (e.g., #horror-requests, #hollywood-requests, #documentary-requests). It would be great if a single instance could be used to separate downloads by genre tag, as suggested here, or by the channel the bot is listening on.

**Comment by darkalfx** [comment]
You cannot do it automatically via movie genres, however with the new custom categories features you can make commands that will map to whatever you wish them to.
