### ISSUE TITLE
.net downloaded to windows temp directory

### ISSUE THREAD

**Issue by spaceboy76** [darkalfx/requestrr#52]
hi, wherever i unzip and run requestrr from it puts some .net files in user\appdata\local\temp\.net....

all dll files are removed from this directory on system reboot

is this user error?

thanks!

**Comment by ReenigneArcher** [comment]
I just had this same problem. I couldn't start Requestrr without deleting the directory
```
%localappdata%\Temp\.net\Requestrr.WebApi
```

**Comment by darkalfx** [comment]
This bug has been fixed in v1.0.14.
I'm therefore closing this issue!
