### ISSUE TITLE
Error:   Will Not Load on startup

### ISSUE THREAD

**Issue by aevans0001** [darkalfx/requestrr#57]
I believe I have tried everything, but a lot of times after startup, Requestrr just won't load back up.  The service says paused and will not restart.  If I run it through command line I get this error

Error:
  An assembly specified in the application dependencies manifest (Requestrr.WebApi.deps.json) was not found:
    package: 'Discord.Net.Commands', version: '2.1.1'
    path: 'lib/netstandard2.0/Discord.Net.Commands.dll'

However, that file is located in the same directory as requestrr.webapi.exe.  Please help, I need it to run completely hidden upon startup

------Update-------
it has something to do with my appdata\local\temp folder.  If i delete that folder it seems to work.

**Comment by spaceboy76** [comment]
same as 52

**Comment by shavedbroom** [comment]
it cant run without a command window, i made a shortcut to the .exe and put the short cut in "C:\Users"USERNAME"\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
and it works fine, i always use group policy to not require anything to logon at boot up (still locks itself after 30 mins)

**Comment by darkalfx** [comment]
This bug has been fixed in v1.0.14.
I'm therefore closing this issue!
