### ISSUE TITLE
Windows 10 Issue - Requestrr will stop launching when using nssm until i change the exe file name

### ISSUE THREAD

**Issue by Deathbot64** [darkalfx/requestrr#58]
Like the title says I have been having an issue where requestrr will randomly stop launching after running for a day or two and wont start up again till I change the name of the exe.

**Comment by ReenigneArcher** [comment]
Same as this issue? https://github.com/darkalfx/requestrr/issues/52

**Comment by Deathbot64** [comment]
I didnt try deleting that. If I get the issue again Ill try that. I haven't had the problem now in about a week or so.

**Comment by Deathbot64** [comment]
> 
> 
> Same as this issue? #52

SO issue happened again. i cant find any of the .net files in my Appdata Folder (on windows). Even Moving the folder with everything for Requestrr to a different drive will cause the same issue until I rename the exe to something new. It wont let me use old names either.

**Comment by ReenigneArcher** [comment]
This is the location.

`%localappdata%\Temp\.net\Requestrr.WebApi`

**Comment by Deathbot64** [comment]
I have no .net folder inside %localappdata%\Temp\. all hidden files are
shown.

**Comment by Deathbot64** [comment]
> 
> 
> This is the location.
> 
> `%localappdata%\Temp\.net\Requestrr.WebApi`

So I am dumb and forgot I changed my temp folder location to another drive a while back. Found it finally and deleted that folder and now it seems to be working (have to reconfig cause I didnt save my settings from before)

**Comment by ReenigneArcher** [comment]
> 
> 
> > This is the location.
> > `%localappdata%\Temp\.net\Requestrr.WebApi`
> 
> So I am dumb and forgot I changed my temp folder location to another drive a while back. Found it finally and deleted that folder and now it seems to be working (have to reconfig cause I didnt save my settings from before)

Interesting... I don't have to reconfigure anything when the .net\Requestrr.WebApi folder is deleted. Far as I know the settings are stored in config folder where the .exe file is located. I'm using a scheduled task to start requestrr and added an action to take care of deleting the corrupt folder before starting.

![image](https://user-images.githubusercontent.com/42013603/101073053-e7679f00-356c-11eb-8504-43166845e053.png)

**Comment by Deathbot64** [comment]
No i wiped everything trying to figure this out. Its all working now.

**Comment by shavedbroom** [comment]
it cant run without a command window, i make a shortcut to the .exe and put the short cut in "C:\Users\"USERNAME"\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
and it works fine

**Comment by Deathbot64** [comment]
I am currently running it with nssm right now and I am not having any
issues. Also this way requestrr starts with my system when it reboots. I
dont always want to login to my remote server to get this working. Nssm is
fine. Deleting the .net folder will just be a work around if it not booting
after awhile until this can be fixed.

**Comment by ReenigneArcher** [comment]
> 
> 
> it cant run without a command window, i make a shortcut to the .exe and put the short cut in "C:\Users"USERNAME"\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
> and it works fine

No window shown if you setup a scheduled task like this. Also doesn't require user to be logged in.

![image](https://user-images.githubusercontent.com/42013603/101090048-0f163180-3584-11eb-85d7-2e075c9b7c8b.png)

**Comment by darkalfx** [comment]
This bug has been fixed in v1.0.14.
I'm therefore closing this issue!

**Comment by Deathbot64** [comment]
Oh awesome. Updating now.
