### ISSUE TITLE
Requestrr.WebApi core-dump when run as service in systemd

### ISSUE THREAD

**Issue by kraft87** [darkalfx/requestrr#6]
I managed to get the bot to function when run through the command line, however when setting it up as a service i am getting a core dump.

**Comment by darkalfx** [comment]
If you have any kind error or reproduction steps, that would be great!

**Comment by kraft87** [comment]
I am on centos 8. For use with command line I extracted the zip, and ran the Requestrr.WebApi, which works. When i use the .service file below, it fails with those errors.  
[journalctl.txt](https://github.com/darkalfx/requestrr/files/4346066/journalctl.txt)
[requestrr.txt](https://github.com/darkalfx/requestrr/files/4346067/requestrr.txt)

**Comment by darkalfx** [comment]
Hello there, 

We took the time today to investigate your issue, it appears that you're missing the following your your requester.txt file:

_**WorkingDirectory=/home/requestrr/requestrr/**_

I hope this helps!

**Comment by kraft87** [comment]
That fixed the problem. Thanks for the help, and for the great app.
