### ISSUE TITLE
[Feature Request] Please integrate overseerr, like you did with Ombi!

### ISSUE THREAD

**Issue by FSCorrupt** [darkalfx/requestrr#61]
[Overseerr](https://github.com/sct/overseerr)

It is similar to Ombi and Works really good (Currently in Alpha).

Would it possible to integrate it in Requestrr?

**Comment by theradiostar** [comment]
Seconded; really enjoying Overseerr so far.

**Comment by costaht** [comment]
Yes, please... Especially because Overseerr will probably kill the buggy Ombi.

**Comment by ephekt** [comment]
Yes please! Will donate, too, if it helps :) Ombi is meh.

**Comment by RevitXman** [comment]
Yes!

**Comment by jpringle03** [comment]
I'd also love to see this!

**Comment by haltdev** [comment]
Any chance this is being worked on?

**Comment by sfxhewitt** [comment]
Yes please!

**Comment by fitur** [comment]
Yes!

**Comment by darkalfx** [comment]
I integrated it in the latest release, **v1.0.15**.

So I'm now closing this issue!
