### ISSUE TITLE
Pressing upvote button too quickly doesn't work

### ISSUE THREAD

**Issue by mlapaglia** [darkalfx/requestrr#65]
if you press the upvote button before the `If you want to request this movie please click on the :arrow_down: reaction directly above this message.` message is sent by the bot the click is not noticed. after clicking the button two more times to remove the reaction and re-add it then it works.

**Comment by darkalfx** [comment]
There isnt much I can do about that at the moment, you have to wait until the message from the bot telling you that you can click on it appears, if you click before that point it won't register the click.

**Comment by darkalfx** [comment]
We are now using slash commands, so this no longer a problem!
