### ISSUE TITLE
Migrate Requestrr

### ISSUE THREAD

**Issue by hackmonker** [darkalfx/requestrr#68]
What do I have to backup to migrate the bot from one server to another?

**Comment by Cruv** [comment]
How are you handling the /config directory the container needs? If its a Bind type mount then all you have to do is move the directory bound to /config and re-map it on the new server. If its a Volume type mount then you have to export the volume to the new system and reattach it. Other than that, the container should come back up as if nothing happened.

**Comment by hackmonker** [comment]
ok I am using volume. will export it and try. thanks
