### ISSUE TITLE
[Feature Request] Use Role IDs instead of Names

### ISSUE THREAD

**Issue by ROODAY** [darkalfx/requestrr#78]
I like the current feature of gating access to the bot to certain roles, helps out on my Discord server where there are a lot of people and not all of them I want to be able to send requests, but recently we changed the names of a couple roles and the bot told everyone that they didn't have the right role. Took a bit to realize the issue was with the name change, but this could be avoided in the future if we can use Role IDs.

**Comment by darkalfx** [comment]
Fixed in the latest update!
