### ISSUE TITLE
[Feature Request] Support for requesting 4K content through Overseerr

### ISSUE THREAD

**Issue by VP-EN** [darkalfx/requestrr#93]
**[Feature Request] Support for requesting 4K content through Overseerr**

**Is your feature request related to a problem? Please describe.**
As of now, it's not possible to utilize Overseerrs 4K library/4K sonarr/radarr option(s). 
Overseerr has native support for separate 4K Radarr/Sonarr servers.. Overseerr also manages user permissions, like who can request 4K, who can't, who can request "normal" content, and who can't .. and so on.

Whenever you request something, using `!movie` or `!tv`, it'll request it through the "default" configured server(s) on Overseerr. 

**Describe the solution you'd like**
It would be nice to have separate commands for the separate 4K Radarr/Sonarr servers, which are configured through Overseerr. So commands like `!4kmovie` and `!4ktv` to request through Overseerr, specifically using the separate 4K Radarr/Sonarr servers. 

**Additional context**
Also asked about this on [Discord](https://discord.com/channels/674782527139086350/674782527688278037/861371852698288168), if that's relevant.

**Comment by milindpatel63** [comment]
4k support would be awesome...but if we are going till there, why not have support for more...like i have 3 radarr/sonarr instances...1080p,4K,dolby vision....so like
!movies1080
!movies4k
!moviesDV
if you guys could collaborate with overseerr,
a simpler approach could be having multiple api's for multiple radarr/sonarr instances of overseerr.....

**Comment by darkalfx** [comment]
I am closing this PR as this is now available in the latest update.
