### ISSUE TITLE
[Feature Request] Slash commands / Buttons / Select menus

### ISSUE THREAD

**Issue by tombomb** [darkalfx/requestrr#94]
its the new hotness
https://blog.discord.com/slash-commands-are-here-8db0a385d9e6
https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons
https://support.discord.com/hc/en-us/articles/4403375759255-Bots-Select-Menus

just to make every thing more pretty.

**Comment by ReenigneArcher** [comment]
Came here to request this same thing

**Comment by chronnick** [comment]
Same

**Comment by darkalfx** [comment]
This has been done in the latest update!
