### ISSUE TITLE
Discord bot not notifying.

### ISSUE THREAD

**Issue by morganzero** [darkalfx/requestrr#96]
Hi, I'm having this issue where my discord bot suddenly stopped notifying when the movie/episode gets available. Any ideas?

**Comment by darkalfx** [comment]
Make sure the presences settings are enable, check the wiki on steps how to do this.

**Comment by morganzero** [comment]
Hmm. Those are both already checked. No idea why the bot suddenly stopped notifying.

Best,
Morgan

**Comment by Darigitin** [comment]
Getting the same issue

![image](https://user-images.githubusercontent.com/12042396/130373588-d2b65cf1-b442-4428-95ed-d262fabc71d7.png)

No notification when movie was finished downloading and available on the plex

**Comment by JoshNotWright** [comment]
Having this same issue as well. But it's not for every movie, and it only seems to be for movies.

**Comment by morganzero** [comment]
If I remember correctly I created a new bot and that fixed it for me.

Best,
Morgan
