### ISSUE TITLE
[Feature Request] Optional Threads

### ISSUE THREAD

**Issue by Varingon** [darkalfx/requestrr#98]
https://discord.com/developers/docs/topics/threads

With threads being introduced, I believe it would be good to be able to enable them as  it would make channels in which the movie bot operates a lot cleaner, e.g. putting all series imports in 1 thread.

**Comment by darkalfx** [comment]
Since the bot now uses slash commands, everything stays within the same message, and they can even be hidden from the channel completely.

I will close the feature, re-open it if you think its still needed and I misunderstood!
